

# Mad Lib
noun1 = input ("Noun")
print("%s." % noun1)
print()
pluralnoun1 = input ("plural noun")
print("%s." % pluralnoun1)
print()
noun2 = input ("Noun")
print("%s." % noun2)
print ()
adjective1 = input ("adjective")
print("%s." % adjective1)
print ()
adjective2 = input ("adjective")
print("%s." % adjective2)
print()
noun3 = input ("noun")
print("%s." % noun3)
print()
pluralnoun2 = input ("plural noun")
print("%s." % pluralnoun2)
print()
noun4 = input ("noun")
print("%s." % noun4)
print()
pluralnoun3 = input ("plural noun")
print("%s." % pluralnoun3)
print()
pluralnoun4 = input ("plural noun")
print("%s." % pluralnoun4)
print()
noun5 = input ("noun")
print("%s." % noun5)
print()
adjective4 = input ("adjective")
print("%s." % adjective4)
print()
print("At the beginning of the life, %s and %s come into play." % (noun1, pluralnoun1))
print("%s is the %s , air, water, and %s and our very own %s is an example of %s." % (noun2, adjective1, adjective2, noun3, pluralnoun2))
print("%s is another big part of the %s of the %s Some examples of %s are heat and %s" % (noun4, pluralnoun3, pluralnoun4, noun5, adjective4))

madlibs = []