

# Mad Lib
noun1 = input ("Noun")
print("%s." % noun1)
print()
pluralnoun1 = input ("plural noun")
print("%s." % pluralnoun1)
print()
noun2 = input ("Noun")
print("%s." % noun2)
print ()
adjective1 = input ("adjective")
print("%s." % adjective1)
print ()
adjective2 = input ("adjective")
print("%s." % adjective2)
print()
noun3 = input ("noun")
print("%s." % noun3)
print()
pluralnoun2 = input ("plural noun")
print("%s." % pluralnoun2)
print()
noun4 = input ("noun")
print("%s." % noun4)
print()
pluralnoun3 = input ("plural noun")
print("%s." % pluralnoun3)
print()
pluralnoun4 = input ("plural noun")
print("%s." % pluralnoun4)
print()
noun5 = input ("noun")
print("%s." % noun5)
print()
adjective4 = input ("adjective")
print("%s." % adjective4)
print()
print ("At the beginning of the life, (noun 1) and (plural noun 1) come into play. (noun 2) is the (adjective 1) , air, water, and (adjective 2) and our very own (noun 3) is an example of (plural noun 2).(noun 4) is another big part of the (plural noun 3) of the (plural noun 4) Some examples of (noun 5) are heat and (adjective 4)

")